 
drop table if EXISTS ods.t_category_nav;
 CREATE EXTERNAL TABLE ods.t_category_nav
 (  id bigint ,
  parent_id int ,
  name string ,
  prefix_tips string ,
  prefix_color string ,
  suffix_tips string ,
  suffix_color string ,
  nav_type int ,
  nav_level int ,
  nav_image string ,
  nav_image_title string ,
  nav_url string ,
  category_ids string ,
  banner_id int ,
  status int ,
  sort smallint ,
  time_search string ,
  days smallint ,
  online_type int ,
  fixed_time int ,
  online_status int ,
  online_start_time bigint ,
  online_end_time bigint ,
  create_by bigint ,
  create_time bigint ,
  update_by bigint ,
  update_time bigint ,
  deleted int ,
  is_sensitive int ,
  show_type int ,
  filter_ids string ,
  nav_marketing_url string ,
  nav_desc_title string ,
  nav_desc_image string ,
  nav_desc_info string ,
  nav_desc_image_app string ,
  nav_desc_info_app string ,
  f_category_ids string ,
  colors string ,
  marketting_type int ,
  marketting_start_time bigint ,
  marketting_end_time bigint ,
  min_app_version bigint 
 ) 
 STORED AS PARQUET
  LOCATION 's3://bidatabase-new/ods/pg/t_category_nav/';
